### ISSUE TITLE
Updating rollup to version >= 0.48 breaks this plugin

### ISSUE THREAD

**Issue by fstoerkle** [phamann/rollup-plugin-hash#9]
As of version 0.48, rollup introduced ["Numerous changes to the `options` object"](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0480).

An overview of the changes can be found in [this gist](https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32).

`rollup-plugin-hash` is not compatible with this new format, and fails during our build with this error:

```
[!] TypeError: path must be a string or Buffer
TypeError: path must be a string or Buffer
    at Object.fs.unlinkSync (fs.js:1067:18)
    at Object.onwrite (.../node_modules/rollup-plugin-hash/dist/rollup-plugin-hash.js:87:8)
    at .../node_modules/rollup/dist/rollup.js:10609:40
    at next (.../node_modules/rollup/dist/rollup.js:148:27)
    at .../node_modules/rollup/dist/rollup.js:152:48
    at <anonymous>
```

Our `rollup.config.js` looks like this:
```
  ...,
  hash({
    dest: 'build/assets/bundle.[hash].js',
    manifest: 'build/assets-manifest.json',
    algorithm: 'sha256',
    manifestKey: 'js',
    replace: env === 'production'
  }),
  ...
```

**Comment by phamann** [comment]
@fstoerkle Thanks for flagging this issue. Are you able to submit a PR fixing the changes? Otherwise I will try and update when I have some time over the weekend.

**Comment by phamann** [comment]
Fixed in #10
